### ISSUE TITLE
Cannot find module 'babel-plugin-module-resolver'

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#1]
Hi @ospfranco , i cloned the project i wanted to try it but i am having the following error:

```
error: index.js: Cannot find module 'babel-plugin-module-resolver'
Require stack:
- /Users/userName/sol/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/userName/sol/node_modules/@babel/core/lib/config/files/index.js
- /Users/userName/sol/node_modules/@babel/core/lib/index.js
- /Users/userName/sol/node_modules/metro-transform-worker/src/index.js
- /Users/userName/sol/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/userName/sol/node_modules/jest-worker/build/workers/processChild.js
```

I also tried to do this, but it doesn't fix the problem:

`npm i --save-dev babel-plugin-module-resolver
`

I performed the following steps:

```
cd sol && yarn
cd macos && pod install && cd ..
yarn start
yarn macos
```

**Comment by ospfranco** [comment]
there is nothing to try, it's just some empty UI for now, should be fixed for now, but don't bother running this for a while

**Comment by Angelk90** [comment]
@ospfranco : In the end, I succeeded.
<img width="810" alt="Schermata 2022-01-17 alle 14 47 12" src="https://user-images.githubusercontent.com/20476002/149780335-5a19ce6a-3e7a-49b6-9960-a44b92892afd.png">
