### ISSUE TITLE
Calculator in launcher

### ISSUE THREAD

**Issue by kylebarron** [ospfranco/sol#101]
Hey there, just tried out `sol` and it's a really cool tool!

One of the things I use most in the default mac launcher as a super quick calculator. I realized that sol doesn't currently support any math. Is this something you'd be interested in adding?
<img width="752" alt="image" src="https://user-images.githubusercontent.com/15164633/213304447-e8463133-718c-482a-a4f2-45e4584f3ad7.png">

**Comment by ospfranco** [comment]
Ah, it seems I broke it, this is meant to work

**Comment by ospfranco** [comment]
Please download the latest version, should be fixed

**Comment by kylebarron** [comment]
thanks, it works now!
