### ISSUE TITLE
How to close this app?

### ISSUE THREAD

**Issue by mateuszmazurek** [ospfranco/sol#103]
There's no "Quit" command in palette, there's no dedicated Sol status icon in MacOS menu bar, I can't even do it using  > Force Quit because Sol is not on the list 🤔 The only way I found is to kill `sol` process via terminal. Am I missing something?

**Comment by ospfranco** [comment]
no, you are right there is no command to close the app. You can use Cmd + Q while the app is open though.

**Comment by ospfranco** [comment]
I added a quit/exit command, will be there on next release.
