### ISSUE TITLE
Extra features went missing after an update.

### ISSUE THREAD

**Issue by allanhortle** [ospfranco/sol#105]
Apologies if this is already a known issue. But Sol just auto updated to a new version and:

* The calendar moved from the launcher to the menu bar.
* Spotify is gone

![image](https://user-images.githubusercontent.com/3760524/227809415-38dfd7db-8507-4c93-955f-64a0e3ef3801.png)

**Comment by ospfranco** [comment]
yup, this is intended, spotify integration was using a private framework which causes the app to crash occasionally. Calendar integration is also now limited to one event, shown close to the time of the event and in the menu bar.

Feel free to leave feedback :)

**Comment by allanhortle** [comment]
Oh man, that's a shame - those two features were my favourite part. I didn't realise how much the calendar integration had changed my workflow until it went away. 

I like an uncluttered menu bar, and so I really enjoyed that every time I opened the launcher I got a glimpse of my schedule for the day. And when I had a meeting it was great to be able to just press `cmd+space tab return` to jump in.

I can understand that some people like more detail in their menubar, and it is better at reminding you when the next meeting is. I'd put in a vote to have both the weekly schedule and the menubar calendar able to be toggled on/off in the settings panel.

**Comment by ospfranco** [comment]
Decided to revive this feature, I also find it useful.

I migrated a lot of the rendering to JS components, so now I'm able to do this:

![CleanShot 2023-04-25 at 15 43 09](https://user-images.githubusercontent.com/1634213/234295926-d7fe4f02-e52b-4f48-b099-3fcdfc19806a.png)

I hope you like the new widget
