### ISSUE TITLE
How do I stop Sol from disappearing in a test environment? 

### ISSUE THREAD

**Issue by josh-may** [ospfranco/sol#106]
This is what I see when I spin up a local server (see screenshare). The app loads up and is shown but when I click away from it,it disappears. 

Is there a way to make the app always show on a local server so I can make edits in real time? 

https://user-images.githubusercontent.com/72312238/229111720-193f0cfb-8412-4b8b-8d3d-b902ea6b43fc.mp4

Thanks,
Josh

**Comment by ospfranco** [comment]
You have to modify the code in AppDelegate.m so that it doesn't hide the window when it looses focus, but it will break a bunch of other stuff

**Comment by josh-may** [comment]
Thanks Oscar!
