### ISSUE TITLE
No source files

### ISSUE THREAD

**Issue by TJTorola** [ospfranco/sol#108]
Where is the source for Sol? All I see is the app contents and built releases ever since https://github.com/ospfranco/sol/commit/51309e22debcdf454b5e1944a0470690ce503c23 a month ago. Looking at https://github.com/ospfranco/sol/issues/102 it sounds like that wasn't the case at one point.

**Comment by ospfranco** [comment]
Removed the source code, got tired of people forking the project to start their own clones and not contributing back. This repo remains here only for issues and as a repo for updates.
