### ISSUE TITLE
Is the Emoji Picker working?

### ISSUE THREAD

**Issue by jkurei** [ospfranco/sol#109]
I'm on the last version of Sol (according to `homebrew`) and I'm having trouble with the emoji picker. It shows up, and it's super fast, but then how do I get the emoji onto the text I'm writing?

With the default emoji picker I can use the arrows and Enter, and the selected emoji appears on whetever it is I'm writing. Doesn't seem to work with Sol's.

Also, there is no way to disable it, as you can do with the clipboard manager or the scratchpad, in Sol's settings. 

PD: Other than this issue, I love Sol, kudos!

**Comment by ospfranco** [comment]
It should be working. Check the app has accessibility permissions on the system settings :)

**Comment by jkurei** [comment]
That was it! 🥳👍🍹🚀⚡

I've been using it without that permission for a long time and this was the only thing not working. May be a warning at the bottom of the Emoji picker if the permission is missing would prevent other people for falling into this.

Thanks!

**Comment by ospfranco** [comment]
I will take a look when possible :)

**Comment by ospfranco** [comment]
I checked again and the code is there, accessibility is checked upon app start and there is a message at the bottom when the app starts telling you to grant accessibility. Probably you denied it when you installed the app, not much I can do afterwards. Closing this for now.
