### ISSUE TITLE
Stop track work time

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#11]
Hi @ospfranco , I'm not quite understanding how to use `Track time`.

I have created several but:
- How exactly they work
- how do I delete a specific one, I tried to use `Stop Track time` but it doesn't seem to work

**Comment by ospfranco** [comment]
It's a turn on/turn off system, I created for myself, anything else is not supported at the moment

Any improvement will have to be discussed. But there are many things that will require a tutorial or an onboarding, which I have no plans to build at the moment
