### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by t18n** [ospfranco/sol#110]
Using React Native is such an excellent choice of technology for this project. Since RN support [cross-platform build](https://reactnative.dev/docs/out-of-tree-platforms), would you consider to support Linux (and potentially Windows) in the future?

**Comment by ospfranco** [comment]
Linux is not supported by RN, nor it looks like it will. Somebody started with some port of windows (code is still in there) but windows doesn't really have a concept of floating UIs available. 

This is a hobby project of mine, so no, no plans to put inordinate amounts of time porting to other platforms.

**Comment by t18n** [comment]
Thank you @ospfranco.
