### ISSUE TITLE
Can't make Sol get calendar permissions

### ISSUE THREAD

**Issue by lajlev** [ospfranco/sol#111]
<img width="600" alt="image" src="https://github.com/ospfranco/sol/assets/133836/77a6a30f-c6eb-4e37-8aba-81abf63f98b9">
<img width="596" alt="image" src="https://github.com/ospfranco/sol/assets/133836/3a1e7737-0788-4663-86c2-d51923432572">
<img width="280" alt="image" src="https://github.com/ospfranco/sol/assets/133836/fffd9518-1f73-4af4-bd3c-3bcf677bc215">
<img width="505" alt="image" src="https://github.com/ospfranco/sol/assets/133836/1a40b61a-8b69-4431-abf1-ebe93b7309d1">

**Comment by lajlev** [comment]
Any clue why it's not showing in calendars? Beside of this Sol auto shutdown every time I try to click this link
<img width="244" alt="image" src="https://github.com/ospfranco/sol/assets/133836/d9295a6d-1246-4856-b6ef-c334ab3f1fa7">

**Comment by ospfranco** [comment]
Ah weird. It's not auto-shutting down. It's crashing hehe. I can take a look later, maybe something broke. Which macOS version are you using?

**Comment by lajlev** [comment]
Sonoma 14

**Comment by ospfranco** [comment]
![Oscar Franco Screen 000334](https://github.com/ospfranco/sol/assets/1634213/af0a3270-46f4-4479-aec9-49ec2865cfd5)

Found the issue. Somebody at apple doesn't understand the meaning of "deprecated" hehe.

**Comment by ospfranco** [comment]
New version is out, please try it and let me know if it works.

**Comment by lajlev** [comment]
Worked like a charm
