### ISSUE TITLE
Ability to ignore certain apps/ folders from search

### ISSUE THREAD

**Issue by JeffersonBledsoe** [ospfranco/sol#113]
## Overview

With Alfred, it would use the same index as Spotlight when performing searches, meaning that anything I didn't want to appear I could simply drop into the `Prevent Spotlight from searching these locations` field in the Privacy tab of the Spotlight settings.

## Proposed solutions

- Sol read from the spotlight index's ignore list to prevent apps and folders being searched that are not wanted
- OR, or a separate 'ignore' list is added to the Sol settings which serves the same purpose

## Additional comments

Just trying out Sol and it's really nice so far, great work!

**Comment by ospfranco** [comment]
Thanks a lot for the kind words!

I disabled file search on the latest versions because it kept crashing the app for some reason. I don't have time to bake it again, you are free to give it a try... it was also super slow compared to proper spotlight

**Comment by ospfranco** [comment]
There is a new file search where you have to manually add the paths you want to search, which means this is now resolved.
