### ISSUE TITLE
Disable emoji picker

### ISSUE THREAD

**Issue by JeffersonBledsoe** [ospfranco/sol#114]
## Overview

The emoji picker that is built into Sol doesn't have a way to be disabled.

## Proposed solution

- Add another shortcut picker similar to the existing scratchpad and clipboard manager pickers that is for the ability to change the shortcut used for the emoji picker. There should be an option to disable it here, the same as the other options

**Comment by ospfranco** [comment]
PRs are welcome :)

**Comment by ospfranco** [comment]
I don't know why would you want this, but creating more shortcuts was too cumbersome. I've just added a toggle to disable the emoji picker. It will be out in the next release.
