### ISSUE TITLE
ChatGPT on Sol?

### ISSUE THREAD

**Issue by p13rrs** [ospfranco/sol#115]
Is possible to put ChatGPT on Sol? I'm not talking about a redirecting link on the website, but about the possibility of giving a question and receinving the answer directly on Sol. (for example, like on Raycast)

**Comment by ospfranco** [comment]
I dislike ChatGPT but I guess there is no point fighting the wave right now. However I have very little free time atm, so PRs are welcome.

**Comment by huzhenghui** [comment]
I use Ollama
```applescript
set userInput to text returned of (display dialog "Please input your question:" default answer "")
set output to do shell script "/opt/homebrew/bin/ollama run llama2-uncensored:latest " & quoted form of userInput
display dialog output 
```
