### ISSUE TITLE
After activation, if I hit return, Postgres launches and takes focus

### ISSUE THREAD

**Issue by ehamiter** [ospfranco/sol#116]
It's the strangest thing. I hit sol's activator, the window prompt comes up, I hit enter/return and expect it to either do nothing or to disappear but instead it launches the Mac app Postgres. I close it, repeat, it launches it again. Mostly curious but I guess I'm also reporting a bug, and am curious if you end up finding the reason.

M1 running Sonoma 14.2.1

**Comment by ospfranco** [comment]
Ah yeah, the return listener is still active in the minimized form. Thanks for noticing, I will take care of it.

**Comment by ospfranco** [comment]
Fix is released in `2.1.16`
