### ISSUE TITLE
Better search ui

### ISSUE THREAD

**Issue by AISLVE** [ospfranco/sol#118]
i would love to see more padding on individual elements like a compact mode and a default mode somewhat like raycast being honest it looks pleasing but I like your app's idea more than theirs just because of the ease of use and minimalism

**Comment by ospfranco** [comment]
Yeah, I always play around with ideas and I liked spotlight a bit better but I have to admit it is a bit crowded. I will change it soon.

**Comment by ospfranco** [comment]
Completely rebuilt the UI in the last version.
