### ISSUE TITLE
Add ability to change search engine

### ISSUE THREAD

**Issue by arcxne** [ospfranco/sol#119]
Some people (like me) don't want to use google.com as the default search engine, especially privacy-minded people.

**Comment by ospfranco** [comment]
PRs are welcome

**Comment by eclecticpassions** [comment]
Can a setting be added so we could add our own search engine of choice like duckduckgo or perplexity even?

**Comment by ospfranco** [comment]
PRs are welcome

**Comment by eclecticpassions** [comment]
I am not tech proficient enough to add the function myself :( hope someone can do it one day. Thanks....

**Comment by ospfranco** [comment]
I've added duckduckgo and bing as alternatives

**Comment by Airgunster** [comment]
@ospfranco Amazing, thanks a lot!

**Comment by eclecticpassions** [comment]
Thank you @ospfranco! Happy holidays 🎉
