### ISSUE TITLE
No events

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#12]
Hi @ospfranco , When there are no events, it would be better not to show anything instead of the image,

There would be more space for scrolling elements.

<img width="773" alt="Schermata 2022-03-20 alle 21 04 50" src="https://user-images.githubusercontent.com/20476002/159183881-9e53568c-83f0-472a-bf26-434d1e4d2f4d.png">

**Comment by ospfranco** [comment]
I dont think scrolling hundreds of Elements is useful

**Comment by ospfranco** [comment]
I get your point though, I'll see what else can be done, but the app really needs an onboarding tutorial
