### ISSUE TITLE
bug: Showing weird characters instead of emojis in menu bar 

### ISSUE THREAD

**Issue by PauloPhagula** [ospfranco/sol#121]
Hi! When the `Show upcoming event in menu bar` is enabled, if the event title has emojis then Sol shows some weird characters instead of the emoji. Screenshots with example below

Event in Calendar app
![Screenshot 2024-05-15 at 12 49 41](https://github.com/ospfranco/sol/assets/6130991/bf5e71f9-ae9f-4c97-97c9-8ef213572d26)

Event in menu bar

![Screenshot 2024-05-15 at 12 49 29](https://github.com/ospfranco/sol/assets/6130991/7e2bc423-b5ad-4835-aff8-3a8b40d27150)

**Comment by ospfranco** [comment]
weird. Thanks I will take a look!

**Comment by ospfranco** [comment]
Will be fixed on next release
