### ISSUE TITLE
Doing Quick Maths in Sol Gives Result Without Allowing Us To Copy Result

### ISSUE THREAD

**Issue by whanata** [ospfranco/sol#122]
I used to use Raycast and it allowed you to do maths on the bar also.

The difference though is Raycast, when you type the `enter` bar, it will save the math result to the clipboard so you can paste it somewhere else.

Could you do this also in `sol`?

Thanks.

**Comment by ospfranco** [comment]
Pressing the enter key should copy the result to the clipboard. I'll take a look later, thanks for noticing!

**Comment by ospfranco** [comment]
Should be fixed in the latest version.
