### ISSUE TITLE
Can I (try to) create an extension for MakeItHome

### ISSUE THREAD

**Issue by cekkr** [ospfranco/sol#124]
Hello,
sorry if I may use the issue section in the wrong way.

I developed MakeItHome ([https://github.com/Geckos-Ink/MakeItHome](https://github.com/Geckos-Ink/MakeItHome)) that it's an UI extender for macOS. Its main use is to allow the rapid switching between application, but supports also widgets in the top zone and now I'm working on "App Extension" where an application can create a view in the area corresponding to the preview of your app.

I was looking for a feature like the one offered by sol for a while, but I used to found closed source solutions where the developers neither reply to my collaboration requests. This is understandable, seen the I have serious difficulties to make my application known.

Short cut: MakeItHome, for the moment, is a sandboxed app and it's very limited on some features: it's practically a work-around software seen what's is able to do. But it has also a simple HTTP server accessible by local application that allows external apps to extend its functionalities. 

So my question is: if I fork it, I try to implement an extension that allows, in some way, to use Sol features from the overscreen with a good result, there is any possibility to merge this feature in the main branch? If not, you have some ideas for such an experiment?

Because I have nearly time to work on MakeItHome itself, I don't think I'm able to maintain a fork and distribute it. And make it known, seen that I cannot advertise it in the App Store version of the app.

Thank you for your time

**Comment by ospfranco** [comment]
I don't quite understand what your app does, nor how it would interact with sol. You can fork it but I won't maintain third party apps integrations. A plugin system like raycast is probably what you are looking for, did you try to that? Otherwise, since I'm the sol contributor, maintaining compatibilty and maintaining third party code is not really on my radar.

**Comment by ospfranco** [comment]
Haven't heard back, will close this for now.
