### ISSUE TITLE
Application text doesn't update with system theme update

### ISSUE THREAD

**Issue by gaurakshay** [ospfranco/sol#125]
Hi, Thank you for this amazing tool.
My macbook is set to change it's appearance based on time of the day. When the theme changes, it seems that the overall colors of the app changes but the text color doesn't change making it difficult to read. If I close out the app and open it again, text colors go back to normal.

## Text colors after system theme changes after sunset

<img width="709" alt="Screenshot 2024-06-10 at 21 28 18" src="https://github.com/ospfranco/sol/assets/17280428/31c23095-96c1-4df9-a135-2e34c2df97f7">

## Text color after restarting the app

<img width="704" alt="Screenshot 2024-06-10 at 21 28 40" src="https://github.com/ospfranco/sol/assets/17280428/e7f15ecf-5afd-4ba6-b2cd-451c4a39270d">

**Comment by ospfranco** [comment]
Unfortunately this is some glitch in the framework itself. I will take a look though

**Comment by gaurakshay** [comment]
Thank you. Please let me know if there is anything I can do to help with this.

**Comment by gaurakshay** [comment]
You're right, manually triggering the theme change does update the application's theme correctly.

**Comment by ospfranco** [comment]
Going to close this, I've discovered some issues if you have reduce transparency in your OS settings but I cannot find the culprit. All the code looks correct. If this is happening again after some updates let me know.
