### ISSUE TITLE
Any application shortcut opens calendar

### ISSUE THREAD

**Issue by rasmus-kristensen** [ospfranco/sol#129]
Hello,

Sol sol 2.1.58
OSX Sonoma 14.5

I'm facing a very strange issue, from time to time SOL will bug out and only open Calendar regardless of what application I select in the launcher.
Even sols own settings or quit functionality opens the calendar, restarting the app sometimes fixes the issue.

I've added a video showcasing the issue.

https://github.com/ospfranco/sol/assets/106582326/a4d246d1-1002-4911-a10f-1c24fa7c41bc

**Comment by ospfranco** [comment]
Hmm interesting, this usually happens on development because the keyboard listeners are not registered properly. Do you have nay more details to share? Does it happen after awaking the computer from sleep? After opening an item before?

**Comment by ospfranco** [comment]
Oh nvm, I think I found the issue. Will publish a new release soon.

**Comment by rasmus-kristensen** [comment]
> Hmm interesting, this usually happens on development because the keyboard listeners are not registered properly. Do you have any more details to share? Does it happen after awaking the computer from sleep? After opening an item before?

It's very sporadic when it happens, I usually don't face this issue a lot, sometimes it disappears on its own again but today I've restarted the app several times and it still persists. Could be after sleep yes, today from the awakening of the laptop it was there, but then again other times it has worked flawlessly and suddenly it bugs out in the middle of my work.

**Comment by ospfranco** [comment]
Yeah, it's an error in the code, whenever you have an upcoming appointment it will jump to the calendar always.

**Comment by ospfranco** [comment]
New version is out `2.1.63`, let me know if it fixes the issue.

**Comment by rasmus-kristensen** [comment]
I've installed the update, so far no issues. Thanks for quick response and resolution!
