### ISSUE TITLE
Text input caret not visible

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#13]
Hi @ospfranco , as you can see from the video when it is in light mode it is not clear whether there is focus or not in an input field.

It also happens in the other input fields, for example weather config api.

In the video it can be seen better below because it is zoomed in, but in reality it is not seen.

https://user-images.githubusercontent.com/20476002/159184122-cbc3ec06-3534-4411-8bf6-0d5517857abf.mov

**Comment by ospfranco** [comment]
Unfortunately RN does not allow for detailed customization

**Comment by ospfranco** [comment]
I opened a new issue in the RN-macOS repo

https://github.com/microsoft/react-native-macos/issues/1096

needs to be fixed on the framework before it can be fixed here

**Comment by ospfranco** [comment]
Doubt this will get fixed any time soon, I could create a custom native text input component, but I'm too lazy to do this and this feels like a minor thing, I changed to color to a blue that is not so invisible on the white theme
