### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by V35CH** [ospfranco/sol#130]
Since one of the last updates, when I start sol, noting is displayed anymore. See Screenshot. Even after restart sol and my Mac.
Mac OS 14.5 (23F79)
Sol 2.1.76
![Bildschirmfoto 2024-07-09 um 09 48 20](https://github.com/ospfranco/sol/assets/6399545/feeedce5-41be-420f-b587-44b9dfada307)

**Comment by ospfranco** [comment]
Ah crap... hmmm did you try to re-install? there might be some cache somewhere?

**Comment by V35CH** [comment]
Unfortunately the same, even when I install an older version. I also did a reboot.

**Comment by ospfranco** [comment]
I remember fixing this, this is some native error with AppKit, I will have to fix it later, as I'm currently traveling.

**Comment by V35CH** [comment]
Great, thank you, have a nice trip.

**Comment by gordominossi** [comment]
LGTM 👍🏼 


<img width="812" alt="SOL_2.1.80" src="https://github.com/user-attachments/assets/36042d3f-ed90-48bd-8b56-144882f09c92">

(v2.1.80)

**Comment by V35CH** [comment]
Even after reboot, there are no search results for me.
I have installed the newest Version. 2.1.80.zip
![Bildschirmfoto 2024-07-14 um 19 16 00](https://github.com/user-attachments/assets/78b53ba9-456d-432c-b600-aa88c8d6fb25)

**Comment by jonwest** [comment]
☝️ Same results on my machine as well.

**Comment by ospfranco** [comment]
Reverted some changes in the latest build, let me know if it works for you both

**Comment by V35CH** [comment]
For me it works now v2.1.82. Great Thank you.
