### ISSUE TITLE
Corner Window Management shortcuts

### ISSUE THREAD

**Issue by GoncaloJoseMoura** [ospfranco/sol#131]
Hello Franco!!

Started using this today and i love it. it replaced like 3 applications.
This is just an idea but apps like rectangle have a shortcuts for the corners. so bottom left, top right... that is controlled when the user presses both arrows at the same time.

**Comment by ospfranco** [comment]
I guess you already realized they are there

**Comment by GoncaloJoseMoura** [comment]
Yeah, i apologise. should have looked at the code first.
