### ISSUE TITLE
[Feature Request] - Empty Trash

### ISSUE THREAD

**Issue by itizarsa** [ospfranco/sol#132]
I request a feature to empty bin action similar to Alfred

![SS 5](https://github.com/user-attachments/assets/482187d9-aa4e-4718-b480-713cd92cb5e5)

**Comment by ospfranco** [comment]
PRs are welcome!

**Comment by itizarsa** [comment]
@ospfranco I'm open to adding the feature. Where do I start? Do you have any docs?

**Comment by ospfranco** [comment]
Added some instructions to the README.

**Comment by ospfranco** [comment]
I just implemented this. It will be available on next release.

**Comment by Airgunster** [comment]
@ospfranco Amazing, thank you!
