### ISSUE TITLE
"Blacken menubar" is permanent

### ISSUE THREAD

**Issue by sethrh** [ospfranco/sol#133]
I just downloaded this to try out and was clicking through options. Unfortunately, I pressed the "blacken menubar" option, not entirely sure what it was supposed to do. 

My menubar is now black and inverted, apparently permanently. 

- Unchecking/rechecking the option does not restore the menubar
- Killing the program does not restore the menubar
- Restarting the program and unchecking/rechecking does not restore the menubar
- Switching to dark mode / light mode does not restore the menubar
- LOGGING OUT does not restore the menubar
- REBOOTING does not restore the menubar

It is unclear in the code what exactly you've done to accomplish this, and it's pretty impressive that you've been able to make a systemwide change like this without any special permissions, but tell me how to undo it please.

**Comment by sethrh** [comment]
Ah, you changed my wallpaper and altered my system settings to allow menubar transparency. Perhaps that's why turning the setting off didn't work, maybe the program forgot where it stored a copy of the original image. Or, perhaps you destructively edited my wallpaper. Whatever the case, speaking strictly as a user, this was not a great experience.

**Comment by ospfranco** [comment]
It creates a copy of your wallpaper in the app data dir, none of your images are destroyed. You can just re-set your old wallpaper
