### ISSUE TITLE
[Feature Request] Add ability to open new instance of an application if already open

### ISSUE THREAD

**Issue by zakhikhan** [ospfranco/sol#136]
I use a tiling manager on my mac and work with several different workspaces that I use to organize different tasks and activities. Often times I need to open multiple instances of the same app , such as my web browser or terminal, for different activities, and keep them open simultaneously. On Arch Linux I used the launcher Wofi which by default would open a new instance of an application rather than redirecting the user to already-open instance of that application. It would be great to have this option in Sol, which otherwise is awesome.

**Comment by ospfranco** [comment]
Sol should already open on the screen with focus or with mouse (you can configure which on the settings). Opening multiple app instances would bring a host of synchronization problems and would be a lot of work to maintain. Not going to that. Sorry! :)
