### ISSUE TITLE
Discover aliased applications too

### ISSUE THREAD

**Issue by kriskbx** [ospfranco/sol#137]
Hi. Thank you so much for this amazing tool and all your work on it. ❤️  

Depending on the installation method, some applications might not get installed directly into the `/Applications` or `/Users/username/Applications` folder. Instead, some are installed at a different path and use aliases inside the "Application" folders to link to them. Spotlight is able to pick these up and other tools like raycast as well. It would be amazing, if sol could do this too.

A simple way to reproduce this: Move a random application out of the "Applications" folder, e.g. to the desktop. Create a new alias via right click / make alias and move that alias to the "Applications" folder. Restart sol, it will not pick up the application anymore.

**Comment by ospfranco** [comment]
App discovery is done via:

https://github.com/ospfranco/sol/blob/main/macos/sol-macOS/lib/ApplicationSearcher.swift

If you can get it to show aliased apps, then I can include it in the next release :)

**Comment by kriskbx** [comment]
Thank you so much! This was released in [v2.1.111](https://github.com/ospfranco/sol/releases/tag/2.1.111) 🥳
