### ISSUE TITLE
[Bug?] Calendar event still in menu bar although it is deactivated

### ISSUE THREAD

**Issue by BaldFabi** [ospfranco/sol#139]
In my settings I deactivated the option to show the upcoming event in the menu bar.
![image](https://github.com/user-attachments/assets/06583efc-3859-4d33-99a4-20954bb6f799)

But it's still in the menu bar after a reboot and the automatic launch on startup of sol.
What is strange is that after I close and reopen sol manually, the upcoming event will not be shown.

Could this be a bug or do I miss something?

**Comment by ospfranco** [comment]
Yeah, I have seen this a couple of times but have not managed to reproduce it reliably. It's definitely a bug. Let me see if I can find anything.

**Comment by ospfranco** [comment]
I think I found the problem. Please test new version `2.1.112` and let me know if it is fixed.

**Comment by BaldFabi** [comment]
Seems to work. I would reopen the issue if this happens again, thank you
