### ISSUE TITLE
Give the possibility to set different commands for the start

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#14]
Hi @ospfranco , it would be possible to set different commands for startup, instead of using the `Command + Space shortcut` which also starts `Spotlight`.

A way to be able to register a different command if user wants.

**Comment by ospfranco** [comment]
PRs are welcome

**Comment by ospfranco** [comment]
There is a new onboarding where one is able to select between command + space and option + space, a more custom version will take more time and is not my priority right now
