### ISSUE TITLE
Search no longer finding user applications after v2.1.114

### ISSUE THREAD

**Issue by ben-thebauer** [ospfranco/sol#140]
After being auto-updated to v2.1.114, Sol is no longer able to find any apps in my Applications folder. I did not change any of the file search paths, and when I manually downgrade to an older version it begins working again.

**Comment by ospfranco** [comment]
which applications folder? /Applications or $USER/Applications?

**Comment by ospfranco** [comment]
I need a bit more info than this. I just took another look and things looked mostly fine. I just fixed a minor issue which will be released soon but app scanning is working just fine for me.

- Which OS version are you using?
- Can you pinpoint which version broke it?
- Where are your apps located? /Applications or ~/Applications?

**Comment by ben-thebauer** [comment]
OS Version: macOS Sonoma 14.1.1
Broken version: Have not tested every version, v2.1.110 works for sure
App location: /Applications, though I tested with ~/Applications and it isn't working there either

**Comment by ospfranco** [comment]
Yesterday released a new version. Can you give it a try

**Comment by ben-thebauer** [comment]
The new version does not work either.

**Comment by ospfranco** [comment]
Hmm 2.1.112 is unlikely to be the issue, only did minor cosmetic changes. It's likely 2.1.11. There was a major change done to how apps are listed because someone was using aliases. Here is the PR:

https://github.com/ospfranco/sol/pull/138/files

I guess there is an error being thrown here on your computer:

https://github.com/ospfranco/sol/blob/main/macos/sol-macOS/lib/ApplicationSearcher.swift#L56

The question would be why... Maybe you have some app with special permissions or that fails to get the resources. I can add some logging, since without looking at a stack trace or error message I cannot tell what is wrong.

**Comment by ospfranco** [comment]
I've released a new version 2.1.121. It won't fix the issue but it captures the thrown errors instead of failing silently. Give it a try and I will take a look at sentry later

**Comment by ospfranco** [comment]
There is a new version out 2.1.122. This one won't fail when an app fails to be resolved. But some of your apps might be missing. Sentry logging is there, so I will see which one fails.

**Comment by ben-thebauer** [comment]
Thank you, 2.1.122 works. Interested to see what fails, I don't recall adding any special permission apps or making any changes recently.

**Comment by ospfranco** [comment]
![OSP 000524](https://github.com/user-attachments/assets/b0e9b74e-3b11-401a-ad5d-b04a3de5893d)

Oh wow. this is unexpected.

**Comment by ospfranco** [comment]
I've added a more robust error handling, to try to narrow down which call it's failing. It's released in `2.1.123`, give that one a try.

You can also try one more thing. Give sol full disk access in your System Settings. It shouldn't be needed but maybe it helps.

**Comment by ospfranco** [comment]
Maybe this is you. This is really confusing though. It's like the users Application folder is gone. I've modified the code a bit to try to narrow down the problem even further, give the latest version a go `2.1.126`

![OSP 000526](https://github.com/user-attachments/assets/30ae5ab7-d3a5-4d93-9588-d910ead21104)

**Comment by ben-thebauer** [comment]
That is not me, I just installed the 2.1.127

**Comment by ospfranco** [comment]
![OSP 000530](https://github.com/user-attachments/assets/369ee42e-b864-4821-a575-355b95077e45)
![OSP 000529](https://github.com/user-attachments/assets/8ecbff29-6a69-488d-b1c6-564f0b604803)

Either of these is you? Getting lots of weird errors. But none of them should cause the apps to be completely missing from search.

The other possibility is that the apps are found, but mini search is broken. When you open sol and you scroll down are your apps there?

**Comment by ben-thebauer** [comment]
Neither of those screenshots are me, but your second diagnosis sounds right. When I open sol, the only thing that shows up is calendar info until I begin typing.

**Comment by ospfranco** [comment]
wait what? So application searching is working then.

I'm not quite sure what is the expectation. If you have your calendar integration enabled then it should look like this:

![OSP 000538](https://github.com/user-attachments/assets/df155235-cd61-43ce-9927-a91388ee28b2)

Applications/items are only shown after typing

![OSP 000539](https://github.com/user-attachments/assets/d0b3902b-ca1a-405c-a689-34c0bb9884b0)

If you have calendar integration disabled then you should only get a search bar

![OSP 000541](https://github.com/user-attachments/assets/0c68e949-bf64-40eb-ad0b-0c080d4ef518)

**Comment by ben-thebauer** [comment]
> Thank you, 2.1.122 works. Interested to see what fails, I don't recall adding any special permission apps or making any changes recently.

I mentioned in this comment, when you released version 2.1.122 that works for me. I thought you were looking for a more specific cause.

**Comment by ospfranco** [comment]
Ah haha completely missed that. Cheers then.
