### ISSUE TITLE
Clipboard manager impedes OS clipboard clearing by Bitwarden

### ISSUE THREAD

**Issue by mo-st** [ospfranco/sol#141]
Hi and first off:

\<thanks\>
I really appreciate your work, sol is hands down my favorite spotlight replacement and it's not even close! Thank you for sharing and maintaining such cool software!
\</thanks\>

Now when using password managers I mostly like them to wipe the clipboard after some amount of time, so that the passwords aren't stored somewhere in cleartext. This doesn't seem to work for the clipboard managed in sol, at least not for Bitwarden. I reached out to their support and they acknowledged their wiping only affects the system clipboard and there was nothing they could do about it currently. Given that I didn't grant any special permissions (accessibility was asked for, input monitoring came to mind) I was quite surprised to see that Sol basically stored all my passwords in cleartext without me being able to delete them nor being made aware of this. To be clear, I don't blame you for this, just to explain where I'm coming from here. I also tried `pbcopy < /dev/null` which did not affect the sol clipboard either. I'm honestly quite surprised that software without any special access can just store this data and protect it from external deletion again, I was not aware of that!

For the time being, I decided to disable the clipboard manager completely. My question is, would it be possible to somehow allow the clipboard clearing continue to work or are they just not compatible? I'd like to use the clipboard manager, it seems very useful, but I don't like the thought of password being stored there without the possibility of wiping them.

Thanks for your time.

**Comment by ospfranco** [comment]
Hey, yeah, anything that is added to the pasteboard is listened to on the native code here:

https://github.com/ospfranco/sol/blob/main/macos/sol-macOS/lib/ClipboardHelper.swift#L6

It is then sent to the JavaScript side of things and stored as you mentioned on clear text. This means no matter if the pasteboard is cleared afterwards it won't be deleted from what's already been sent to JS.

However, 1password for example puts things on the pasteboard but makes them not public, so I don't get this behavior. So there is a way to achieve this for Bitwarden but they have probably not figured it out yet. I don't have the time to check if there is anyway to prevent this, but if the app that puts things into the pasteboard does not mark them as "not copyable" somehow there is little I can do from Sol, but if you or someone else wants to take a look PRs are welcome! :)
