### ISSUE TITLE
Correct use of the translate widget

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#17]
Hi @ospfranco , I wanted to try the translator but I can't find it.

**Comment by ospfranco** [comment]
type something then press CMD + 1

**Comment by Angelk90** [comment]
@ospfranco : I would never understand how to use it.

in this way, when can the text sent be large?

**Comment by Angelk90** [comment]
When I do CMD + 1, the browser with the email also opens.

**Comment by ospfranco** [comment]
- don't understand the question 
- I know, this needs a tutorial 
- there is some problem with listeners/mobx and hot reload, do a hard reload and it will work fine

**Comment by Angelk90** [comment]
@ospfranco : In this case with the call how can you not have problems with cors?

**Comment by ospfranco** [comment]
CORS is a browser feature, react-native can do requests to wherever it pleases

**Comment by Angelk90** [comment]
@ospfranco , Ok, it would have been nice if the browser worked.

I did a test with the script on `react-native`, using my device as an emulator.

It works well, but the console comes back to me with a strange problem:

```javascript

translatorLanguage.tsx (113:35)
Parsing error: Unexpected token, expected ";"
(ESLint)
  111 |       try {
  112 |         
> 113 |         length = /^\d+/.exec(json)![0]
      |                                   ^
  114 | 
  115 |         json = JSON.parse(
  116 |           json.slice(length.length, parseInt(length, 10) + length.length), (null)
```

Does that check serve to verify if it is not `null`?
Why haven't you used `RegExp`?

P.s.
That semicolon at the beginning what is it for?

`        ;(json[1][0][0][5] as any).forEach(function (obj: any) {
`

Link: [snack](https://snack.expo.dev/yNwAq8mPE)

**Comment by ospfranco** [comment]
I don't know which code are you pointing me to, that looks like the code from the translation library but that shouldn't be your concern, I meant more about language handling and the list of supported languages.

https://github.com/ospfranco/google_translate_supported_languages

**Comment by ospfranco** [comment]
Will take care of setting translation languages and the whole setting UI for it later
