### ISSUE TITLE
Problems with permissions

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#18]
Hi @ospfranco , once permission to execute a command has been denied, for example:

- Dark mode
- AirDrop

If you try to start it later, nothing happens.

Correct use:
I think if the first time you deny the permission, if you later try to start it, it should ask for permission again.
Instead it does nothing.

**Comment by ospfranco** [comment]
not possible, macOS limits permission requests to a one time only

**Comment by Angelk90** [comment]
@ospfranco : this is a real problem.

**Comment by ospfranco** [comment]
Nothing can be done about it, this is a macOS limitation, but chill man, the product is very early right now, I know all the stuff you are complaining about, but this requires a lot more thought, Settings views, more configuration variables, etc.

If this is important to you, you can start sending pull requests

**Comment by Angelk90** [comment]
@ospfranco : Is there any way to reset everything?
For example to run Dark mode and AirDrop what permissions do they need?
