### ISSUE TITLE
Cannot proceed with onboarding (1.0.2)

### ISSUE THREAD

**Issue by Seiyial** [ospfranco/sol#21]
Hi @ospfranco, I saw Sol in my ProductHunt newsletter and I can't wait to try it out and add all my command shortcuts to it.
I downloaded the latest release 1.0.2 (4h before this is posted), dragged it into my Applications folder, double clicked it and saw this.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/25403498/159337929-799d9947-9850-4e3b-8a08-f6632dc91dd1.png">

Problem is, when I press enter (aka return), cmd+enter, ctrl+enter or anything else, there's no response. I can't get past this page. If I click outside or cmd+tab away, the above window disappears, and when I use cmd+space or double click Sol in `/Applications` again the above page shows up again (and I can't do anything about it, other than click away to make it disappear).

Here's my system specs:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/25403498/159338188-729434c0-599d-4a0b-bc36-1667cd27f1cb.png">

Thank you for building something (at least seemingly for now) amazing!

**Comment by ospfranco** [comment]
Weird, I'll take a look ASAP but it's a bit late here, so maybe tomorrow, can you try with the older version? also, there are currently no customizable shortcuts! something that I will definitely work asap though

**Comment by ospfranco** [comment]
Please try again with the latest version https://github.com/ospfranco/sol/releases/tag/1.0.3 should be working now

**Comment by Seiyial** [comment]
It's working now. Thanks!!
