### ISSUE TITLE
Spotlight being displayed & not all apps appearing

### ISSUE THREAD

**Issue by DillonB07** [ospfranco/sol#22]
... I think the title is pretty self-explanatory, but when I press ⌘+ Space Spotlight appears on top of Sol.

Really cool project though! However I also noticed that the apps in `/Users/<user>/Applications` doesn't appear in Sol. Just in `/Applications`. Would you be able to implement this in the future please? I generally install apps locally rather than globally so this project is useless for me without it.

**Comment by ospfranco** [comment]
yeah, the current binding is hardcoded to command + space, so you need to unbind spotlight before you can use this, the next version will allow to select another binding

Got you on the /Applications folder, will do it soon

**Comment by DillonB07** [comment]
Awesome! Thanks for the speedy response! How do you unbind Spotlight though? I did some research and couldn't find out how to disable it.

**Comment by ospfranco** [comment]
You can try the latest release https://github.com/ospfranco/sol/releases/tag/1.0.3 should display the user-specific applications

**Comment by ospfranco** [comment]
This should be working now
