### ISSUE TITLE
Grant Sol access to your Calendar under System Preferences

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#23]
Hi @ospfranco , at the first start, as you can see from the image it tells me to `Grant Sol access to your Calendar under System Preferences` but if you see above I have already given access otherwise the events would not appear.

<img width="749" alt="Schermata 2022-03-22 alle 19 01 17" src="https://user-images.githubusercontent.com/20476002/159546427-105077c2-d981-43c9-82d8-477c4cef0e2e.png">

**Comment by ospfranco** [comment]
still working on this

**Comment by ospfranco** [comment]
Cannot reproduce, you probably need to restart the app

**Comment by ospfranco** [comment]
nvm, found it
