### ISSUE TITLE
Track time negative hours and minutes

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#25]
Hi @ospfranco , why is it that when I run a newly created track time it gives me negative hours and minutes?
<img width="96" alt="Schermata 2022-03-22 alle 19 09 20" src="https://user-images.githubusercontent.com/20476002/159547590-bdf21bc6-e228-4d35-abf6-5bbfda75b9db.png">

**Comment by ospfranco** [comment]
I set the time only on application open, this is still WIP and also minor

**Comment by ospfranco** [comment]
Fixed
