### ISSUE TITLE
TypeError: Cannot convert undefined value to object

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#32]
Hi @ospfranco , i am getting the following error:

<img width="955" alt="Schermata 2022-04-01 alle 21 19 33" src="https://user-images.githubusercontent.com/20476002/161327996-087c073e-f341-4330-a990-f1739e01a005.png">

When I try to open it `cmd + space` opens sol and then closes right away.

**Comment by ospfranco** [comment]
I don't seem to be able to reproduce it, are you sure you are on the latest changes?

**Comment by Angelk90** [comment]
@ospfranco : I cloned the project with the latest changes.

**Comment by ospfranco** [comment]
I added some default values to the store, maybe that will fix it

**Comment by Angelk90** [comment]
This is what is happening now, it opens and closes right away.

https://user-images.githubusercontent.com/20476002/161373420-e5aaca51-d633-4b8e-a4c7-41488c46ae64.mov

**Comment by Angelk90** [comment]
@ospfranco : it is normal to receive this message in the console?

```
2022-04-02 10:16:16.789 xcodebuild[12610:76799] 
Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications 
for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

2022-04-02 10:16:16.789 xcodebuild[12610:76799] 
Requested but did not find extension point with identifier 
Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier 
for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS 
of plug-in com.apple.dt.IDEWatchSupportCore
```

**Comment by ospfranco** [comment]
I cannot reproduce it, you probably built some temporary version and that messed up the state of the store.

You can try to delete the storage file at: `~/Library/Application\ Support/com.ospfranco.sol/RCTAsyncLocalStorage_V1` and see if that works

**Comment by Angelk90** [comment]
@ospfranco :

I deleted both:

- `~/Library/Application\ Support/com.ospfranco.sol/RCTAsyncLocalStorage_V1`
- `/Users/userName/Library/Developer/Xcode/DerivedData`

I am currently getting the following error:

```
Possible Unhandled Promise Rejection (id: 3):
Error: Failed to write manifest file.Error Domain=NSCocoaErrorDomain Code=4 "The folder “manifest.json” 
doesn’t exist." UserInfo={NSFilePath=/Users/userName/Library/Application Support/com.ospfranco.sol/
RCTAsyncLocalStorage_V1/manifest.json, NSUserStringVariant=Folder, NSUnderlyingError=0x600003dcf030 
{Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

Error: Failed to write manifest file.Error Domain=NSCocoaErrorDomain Code=4 "The folder “manifest.json” 
doesn’t exist." UserInfo={NSFilePath=/Users/userName/Library/Application Support/com.ospfranco.sol/
RCTAsyncLocalStorage_V1/manifest.json, NSUserStringVariant=Folder, NSUnderlyingError=0x600003dcf030 
{Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by ospfranco** [comment]
it's better if you delete the entire folder (`com.ospfranco.sol`) and did you also rebuild the app? like I said, I cannot reproduce it, even if I delete all the data from my computer

**Comment by Angelk90** [comment]
@ospfranco : I just deleted the whole folder com.ospfranco.sol, error seems to be due to AsyncStorage.

**Comment by ospfranco** [comment]
Like I said, I cannot reproduce it, so you will have to solve it on your own, sorry
