### ISSUE TITLE
Sol is not compatible with Homebrew Cask Standard Livecheck

### ISSUE THREAD

**Issue by aemi-dev** [ospfranco/sol#41]
Hi Oscar,

I'm trying to [PR](https://github.com/Homebrew/homebrew-cask/pull/124528) a cask on Homebrew for Sol but the cask could not correctly verify whether it's the latest or not.

Homebrew performs a livecheck when installing a cask according to different methods (described in the [documentation](https://docs.brew.sh/Brew-Livecheck)).

However, you're currently providing 2 ways to get the last version of Sol:
- The GitHub release mechanism
- The Sparkle auto-update mechanism

And there's currently 3 version numbers displayed on GitHub:
- 1.1.20 latest release in ([GitHub Releases](https://github.com/ospfranco/sol/releases))
- 1.1.23 in [`releases`](https://github.com/ospfranco/sol/tree/main/releases) folder of the repo
- 1.1.25 as the latest tags available in [repo tags](https://github.com/ospfranco/sol/tags)

So to set up the livecheck in the [PR](https://github.com/Homebrew/homebrew-cask/pull/124528), I have to ignore the latest tag which does not contain the built application and I have to whether deal with:
- Sparkle [`appcast.xml`](https://github.com/ospfranco/sol/blob/main/releases/appcast.xml)
or
- [GitHub Releases](https://github.com/ospfranco/sol/releases).

But as you know, these two contain 2 different version numbers.

To fix the global problem we have here, I would suggest few fixes:
- to publish a new GitHub release in the same time you update the release in the Sparkle [`releases`](https://github.com/ospfranco/sol/tree/main/releases) folder
and/or
- to build the application for every tag you create or keep the latest tag the one with the built application.

**Why building for every tags?**

>**Only use the `GithubLatest` strategy when it’s necessary and correct**. `github.com` rate limits requests and we try to minimize our use of this strategy to avoid hitting the rate limit on CI or when using brew `livecheck --tap` on large taps (e.g. homebrew/core). The `Git` strategy is often sufficient and we only need to use `GithubLatest` when the “latest” release is different than the newest version from the tags.

The above quote from the official [Homebrew documentation](https://docs.brew.sh/Brew-Livecheck#creating-a-check) explains that the standard behaviour (retrieving the last update by getting the last tag of the repo) is preferred to the `GithubLatest` method I'm using in the current [PR](https://github.com/Homebrew/homebrew-cask/pull/124528).

Nevertheless, it could be nice to keep it consistent by publishing the latest correct version everywhere.

**Comment by ospfranco** [comment]
I can update the latest tags to all match, but keeping the latest tag always populated is not really a good solution. Sometimes I need to do testing and I play around with tags quite a bit. Or prepare to do a release and end up not releasing it. Would it be possible to use the appcast.xml only?

**Comment by ospfranco** [comment]
Yeah, it would be better, the releases page was just the easiest solution at the time, but I might as well just drop it and use the appcast only.

Thanks for taking the time to create the cask though! really appreciate it!

**Comment by aemi-dev** [comment]
Yes, noted. I completely understand. Let's do that.

You're welcome! ;)
