### ISSUE TITLE
How to select/deselect calendars (or give them a priority)? 📆

### ISSUE THREAD

**Issue by nicokosi** [ospfranco/sol#48]
Hello,
As an Alfred user, I am curious about Sol. 😎 
I have just installed it and I have questions about the calendar integration. 📆 

I have 1 personal calendar and 2 professional ones and I would like to show the events from my personal calendar, at least:
<img width="1440" alt="Screenshot 2022-08-10 at 07 12 38" src="https://user-images.githubusercontent.com/3862051/183821362-2cd12379-7eb4-46ea-92fe-c1ede42b6227.png">

Do you know why the personal events are not visible? Maybe that only the first three events are shown? 
Are there any way to select/deselect calendars or to give them a priority?

**Comment by ospfranco** [comment]
[Only the first three events are shown indeed](https://github.com/ospfranco/sol/blob/main/src/widgets/calendar.widget.tsx#L21) no support for further filtering atm. PRs are more than welcome, but first it would be ideal to discuss a bit how would you imagine this working.

**Comment by nicokosi** [comment]
> [Only the first three events are shown indeed](https://github.com/ospfranco/sol/blob/main/src/widgets/calendar.widget.tsx#L21) no support for further filtering atm. PRs are more than welcome, but first it would be ideal to discuss a bit how would you imagine this working.

OK, thank you! :+1: 
Not sure to have clear ideas about how it could evolve, so I close this issue for now.

**Comment by ospfranco** [comment]
I do get that full day events are maybe not that important though, especially if you have an appointment coming soon... I will tweak the logic a bit later, but thanks for reporting!

**Comment by ospfranco** [comment]
I got a bit lazy to write some complex logic to show (or not) all day events when there is no other event available, but I figured for those the OS notifications are enough, so for now I'm hiding them
