### ISSUE TITLE
 WARN  Sending `onShow` and `keyUp` with no listeners registered.

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#5]
Hi @ospfranco , I'm getting the following warms when I start sol.

```
 LOG  Running "sol" with {"rootTag":1,"initialProps":{}}
 WARN  Sending `onShow` with no listeners registered.
 WARN  Sending `keyUp` with no listeners registered.
```

<img width="610" alt="Schermata 2022-03-19 alle 23 18 58" src="https://user-images.githubusercontent.com/20476002/159140381-20953e7e-69d9-4ce8-abf1-e342b27ab0b1.png">
<img width="604" alt="Schermata 2022-03-19 alle 23 19 12" src="https://user-images.githubusercontent.com/20476002/159140384-ae18286b-c32a-44e7-acad-d9dabb89719f.png">

**Comment by ospfranco** [comment]
I added some check to the native key emitters, try on main, should not emit any warning now

**Comment by Angelk90** [comment]
@ospfranco : It seems to be giving no errors now, what could be the problem?

**Comment by ospfranco** [comment]
you can check out the commit I did to fix it
