### ISSUE TITLE
download button should download latest version

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#50]
https://www.solapp.io/ has a nice download button. But instead of downloading the latest version it directs users to https://github.com/ospfranco/sol/tree/main/releases showing downloads from old to new in confusing order.

It would be great if a click on download would just download the latest version.

**Comment by ospfranco** [comment]
Feel free to submit a PR, but it is a static site:

https://github.com/ospfranco/site_sol

**Comment by foss-** [comment]
I know how that works, sadly I am not a developer so you wouldn't not want to deal with my PRs. Do you only want feature requests from people willing to personally work on what they file? Am aware Feeder has such a policy, so in that case feel free to close this issue.

**Comment by ospfranco** [comment]
[I encourage ppl to submit PRs because I don't work for free](https://ospfranco.com/post/2022/07/27/sustainable-open-source-manifesto/) but just leave it open and maybe I will get to it when I have time

**Comment by ospfranco** [comment]
I took a quick look but there is no easy way to get a download link from brew which automatically parses the appcast.xml which contains the info about the latest release, I would have to manually try to parse the file structure in the github repo... which is not really worth my time atm. I will close for now, it's not pretty but it works.
