### ISSUE TITLE
open file in finder when pressing cmd+enter

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#51]
Most launcher allow to open a file in finder when pressing `cmd+enter` with a file selected from search results. Would be great if this was also possible with Sol.

**Comment by ospfranco** [comment]
duplicate of #45

**Comment by ospfranco** [comment]
Now that file search is there, this is valid

**Comment by ospfranco** [comment]
Folder should now be open, selecting it in finder is another story though... I might have to resort to an AppleScript to do that, but I have to find time
