### ISSUE TITLE
window manager: extend options to also use quarter screen

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#52]
[https://github.com/rxhanson/Rectangle](https://github.com/rxhanson/Rectangle) shows nice default keyboard shortcuts which could be used to allow Sol window manager to also support quarter screens.

**Comment by ospfranco** [comment]
I kinda decided against it, because it adds complexity to the product, but I might revisit the idea if enough people ask for it

**Comment by foss-** [comment]
This is certainly use-case dependent. I can see how left and right is sufficient on a laptop. However if sitting in front of a 43" monitor the quarters are *really* useful. Thanks for considering.

**Comment by ospfranco** [comment]
Will be there on the next version

**Comment by ospfranco** [comment]
Released

**Comment by foss-** [comment]
Verified in 1.1.49 and thanks for implementing this nice addition.

Two things, let me know if you want separate issues for those:

1. the windows are overlapping horizontally (not much, but would be nice to have them fit):
![overlap](https://user-images.githubusercontent.com/5708172/185736657-1b492150-300e-43b7-9309-e6bf52e2d423.png)
2. I know of at least one friend heavily using top and bottom half of screen on their laptop (don't personally use that often), but that would somewhat be a logical addition to `ctrl+alt+up|down arrow` since left|right arrow already work that way for left | right half of screen.

**Comment by ospfranco** [comment]
1. There are certain windows that do not go below a minimum size, that can cause some issues, but maybe you are right, I did some simple resizing logic
2. sure

**Comment by foss-** [comment]
1. solved by https://github.com/ospfranco/sol/commit/5cbf74fe96b15e2458ff42973b6db150151594e6 🌻
2. followup https://github.com/ospfranco/sol/issues/66
