### ISSUE TITLE
Multiple displays

### ISSUE THREAD

**Issue by redii** [ospfranco/sol#53]
Hey Oscar,

saw you on HN today, great tool keep it up!

I was using Alfred before and noticed one minor difference. With multiple displays Alfred (and I think default spotlight search too) shows the searchbar on the display on which my mouse is at the moment. With sol it comes up on the display where my focused application is.

Maybe if you have time, that would be a nice little thing to add.

**Comment by ospfranco** [comment]
Will be there on the new version
