### ISSUE TITLE
Padding to bottom

### ISSUE THREAD

**Issue by uwussimo** [ospfranco/sol#54]
Can't see the interface, launcher is padding to bottom leaving blank space.
![Screen Shot 2022-08-11 at 10 55 51](https://user-images.githubusercontent.com/91214940/184072488-6764d087-43df-4d72-8a3d-507a75fdf00f.png)

**Comment by ospfranco** [comment]
duplicate of #46

**Comment by uwussimo** [comment]
my apologies
