### ISSUE TITLE
Error shows up while typing map

### ISSUE THREAD

**Issue by etherealSunshine** [ospfranco/sol#56]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/81072340/184335460-6e122b9d-5954-4b36-b354-42ff506ad5a1.png">

**Comment by etherealSunshine** [comment]
this only happens when everything is lowercase, on typing Map, it doesn't happen

**Comment by ospfranco** [comment]
It is not an error, it's just the JavaScript evaluator. But I will see if there something to be done about it

**Comment by ospfranco** [comment]
Will be there on the next release
