### ISSUE TITLE
show keyboard shortcut for clipboard manager

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#57]
**Currently**

When unaware of keyboard shortcut for clipboard manager, there is no way to learn about it, if a user forgot about it from the initial tutorial.
![1](https://user-images.githubusercontent.com/5708172/184410517-910651a1-f949-4f9e-a6f4-777a7b29d2ed.png)

**Expected**

Why not show the keyboard shortcut (if not invoked from keyboard shortcut) and give users the chance to learn.

**Comment by ospfranco** [comment]
Will be on the next version
