### ISSUE TITLE
Find applications in subfolders of applications folder or outside default applications folder

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#58]
**Currently**

Applications in subfolders are not found e.g. `/Applications/ScanSnap/ScanSnap_Manager.app`.

This also applies to applications which reside outside the applications folder like `/Users/Username/Applications/JDownloader 2.0/JDownloader2.app`

**Expected**

Would be nice to also open those applications from Sol. Interestingly applications like `Activity_Monitor.app` located in the `Utilities` folder are found.

**Comment by ospfranco** [comment]
The applications on the Utilities folder I added manually as a path scan, for nested subfolders I did not take into a account, PRs are welcome

**Comment by ospfranco** [comment]
Will be there on next release

**Comment by foss-** [comment]
Verified with 1.1.48.

ScanSnap and other software in subfolders of applications folder are now showing up. Thank you.

However `/Users/Username/Applications/JDownloader 2.0/JDownloader2.app` is still not showing, which is probably expected. Let me know if you think a separate ticket for that makes sense or if adding that location is out of scope / unwanted.

**Comment by ospfranco** [comment]
I assume that was the folder that was causing the crash starting on 1.1.42 and so on, I can give it a try later

**Comment by ospfranco** [comment]
Will be there on the next version

**Comment by ospfranco** [comment]
It's released, let me know if you find any issues

**Comment by foss-** [comment]
Awesome! This works great so far in 1.1.49. Sol feels more complete now :)
