### ISSUE TITLE
Set the coordinates and the API key

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#6]
Hi @ospfranco , I created a file called `env.json` in the main dir.

I wanted to try to set the values but I'm not really understanding how to do it.

I am doing a similar thing.

```
WEATHER_API_KEY=MYCODE
```

But it appears that the code is not being taken in the store.

I also un-commented the `config.ts` file.

**Comment by ospfranco** [comment]
I changed this, the env.json file is no longer being used, there is a in-app command to set the API key and the coordinates.

<img width="745" alt="Screenshot 000011" src="https://user-images.githubusercontent.com/1634213/159150912-8896c280-76d8-45e2-987b-4400791bb1a4.png">

**Comment by Angelk90** [comment]
@ospfranco : 

<img width="782" alt="Schermata 2022-03-20 alle 12 18 56" src="https://user-images.githubusercontent.com/20476002/159159727-38aa5bca-101d-45b8-884e-2130df441cac.png">

even if i put all the data, how do i confirm?

**Comment by Angelk90** [comment]
@ospfranco : In case there is no `apiKey` and no audio application open, wouldn't it be better not to show it?

<img width="785" alt="Schermata 2022-03-20 alle 12 14 04" src="https://user-images.githubusercontent.com/20476002/159159961-baea5990-f1ca-4e62-bc29-30021962c686.png">

**Comment by Angelk90** [comment]
<img width="741" alt="Schermata 2022-03-20 alle 12 27 38" src="https://user-images.githubusercontent.com/20476002/159160016-2bbdaa3e-214b-4427-8d6f-95591b3d7e56.png">

If an invalid code is entered, for example, I get this, after reloading, closing and reopening sol.

**Comment by ospfranco** [comment]
feel free to open pull requests for all this stuff, so far I've developed this app for myself, it is very unpolished
