### ISSUE TITLE
How to use features

### ISSUE THREAD

**Issue by theklr** [ospfranco/sol#60]
Would love to be able to use the features listed on the site and in the readme, but where is the how to use guide?

**Comment by ospfranco** [comment]
There won't be any, if the product needs to be explained it's already too complex. Searching for items should already teach you shortcuts and there are no more complex interactions. Feel free to leave more specific feedback on how to use specific features though.

**Comment by theklr** [comment]
Well my experience seems to be disjointed from what's presented. I'm not seeing the ability to customize or add features, and currently it mostly queries to google
![Screen Shot 2022-08-15 at 5 03 02 PM](https://user-images.githubusercontent.com/6653320/184718435-d2dfcc56-b1d6-4f37-aa46-1d84a5c6092e.png)

**Comment by ospfranco** [comment]
What exactly do you want to customize? Just search for "settings"

There are no features to add, this is probably not a complex tool as you are imagining. Not close to the level of raycast or Alfred.

**Comment by theklr** [comment]
I searched, but i keeps loading to google

**Comment by theklr** [comment]
Well my current experience seems disjointed from the photos. I’m not seeing any of the features mentioned nor a preferences or help menu to review settings to debug

**Comment by ospfranco** [comment]
Ok, open to feedback here, what exactly are you missing? Have you tried click on the sol icon on the bottom left corner or opening via shortcut (⌘ + comma) or searching for settings? or searching emoji?
