### ISSUE TITLE
Clipboard history search does not seem to work

### ISSUE THREAD

**Issue by hwbehrens** [ospfranco/sol#61]
After invoking the clipboard history pane, typing anything in the search field does not filter the results. I thought maybe pressing Enter was required to trigger the search, but that just pastes the highlighted line.

I assume that since there is a search field, this is either a bug or perhaps a future feature that simply hasn't been implemented yet.

This is on Sol 1.1.40, MacOS 12.5 (21G72), on an M1 Pro chip.

**Comment by ospfranco** [comment]
Ah probably didn't implement it, thanks for noticing.

**Comment by ospfranco** [comment]
Will be there on next release
