### ISSUE TITLE
Latest automatic update broke my preferred main shortcut.

### ISSUE THREAD

**Issue by tdsanchez** [ospfranco/sol#62]
I use option-space to activate Sol and the latest auto-update (I can't ID version because it's not visible anywhere) broke that key combo.  After I press it one time and briefly see Sol's UI, it won't work again until I restart the app.

Additionally, ability to edit keyboard shortcuts is also broken.  When I try to select any of the three drop-downs I can only see choices for the clipboard shortcut and selecting either of those choices has NO EFFECT on any shortcut.  There is NO WAY to edit shortcuts currently so I can't use Sol unless invoked with a double click in the applications folder, making it totally useless.

Please roll back the latest update.

I was really liking this app but it's lack of "mac-like" features (command-comma to get settings, a basic compliment of menus for example) makes it a gui app without any kind of standard interface and makes it extremely hard to use if the shortcut key is broken as it is now.

**Comment by tdsanchez** [comment]
I can now see that the version is 1.1.44 - Version was not visible in the finder when I submitted the issue.

**Comment by ospfranco** [comment]
There seems to be a crash happening at the moment. At the same time I work on this project on my free time, so a fix or a rollback might take some time.

**Comment by ospfranco** [comment]
gotta love open source... in any case 1.1.46 but I still haven't been able to locate the cause of the issues
