### ISSUE TITLE
Command + comma to open settings

### ISSUE THREAD

**Issue by s-oram** [ospfranco/sol#64]
Many Mac applications use the `cmd` + `,`  shortcut to open application preferences. Would you be open to a PR that adds this shortcut to Sol?

**Comment by ospfranco** [comment]
Yep, PRs are welcome

**Comment by s-oram** [comment]
Thanks, I'll give it a shot 🙂

**Comment by foss-** [comment]
Why not leave the issue open until the implementation is in place? Until then this will allow other users to subscribe instead of re-filing the same issue falsely as duplicate.

**Comment by ospfranco** [comment]
I got this working right now, will be there on next release

**Comment by foss-** [comment]
Verified in 1.1.51. This is a nice addition. I actually tried `cmd+,` but was confused nothing happened, only to learn much later, that settings indeed existed inside of Sol. So this addition is very welcome.

**Comment by s-oram** [comment]
Thanks @ospfranco
