### ISSUE TITLE
Permission request dialogs hidden behind Sol search results

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#67]
Thanks for https://github.com/ospfranco/sol/issues/45

Sol ran into a hang showing as Not Responding in Activity Monitor when searching for `Download` and trying to open Downloads folder from search results. The reason became clear upon force quitting Sol: the permission request to access Downloads then showed. I am wondering if that permission dialog was hidden behind Sol. Unsure how to ensure permission requests become visible and don't land behind Sol search results.

**Comment by ospfranco** [comment]
They are automatic by the OS once the app tries to access a protected file path. That's weird though, the window should hide itself once it losses focus. I can try to take a look later.

**Comment by ospfranco** [comment]
I'm not able to reproduce this, if somebody has this issue, comment here and I will re-open the issue.
