### ISSUE TITLE
Declined calendar items are shown 📆

### ISSUE THREAD

**Issue by nicokosi** [ospfranco/sol#68]
Hello! 👋

Calendar items that have been declined are shown in `Sol 1.1.52`. For instance, `Stand-up RUN DSI` is displayed:
<img width="976" alt="Screenshot 2022-08-22 at 05 34 16" src="https://user-images.githubusercontent.com/3862051/185841210-e54f6344-089f-42fb-9f9e-1ae66b5b8959.png">

I think that declined items should not be visible. 🙈

**Comment by ospfranco** [comment]
You are right! I will take care of it later

**Comment by ospfranco** [comment]
Turns out this is not so easy, cancelled events have their status returned as 3 but there is no info if the logged user rejected the invitation, one needs to iterate over the atendee list and find the correct user... which is more than a 5 minute fix... I will take a look later

**Comment by ospfranco** [comment]
Declined items will be not shown on the main view anymore, but they will appear with a line-through when a search is triggered

**Comment by nicokosi** [comment]
That's awesome! 😎
Here is a screenshot (animated GIF) with my own calendar with Sol 1.1.70:
![hidden_calendar_items_in_Sol](https://user-images.githubusercontent.com/3862051/188783547-d2bc8208-55f4-49a3-a51f-8e30cf302915.gif)
