### ISSUE TITLE
Clipboard Filtering Bug

### ISSUE THREAD

**Issue by hwbehrens** [ospfranco/sol#70]
Oscar, thanks so much for implementing the clipboard history filtering! It's working well, and quite fast. I check for Sol updates almost first thing every day.

I just wanted to report a small bug in the new functionality, which is that the selection index/offset is not updated logically during filtering.

For example, if my clipboard history is:

- > Foo
- Bar
- Baz

When I type "ba" in the filter field, then the list correctly shows (with updated highlight):

- > Bar
- Baz

But then, when I press enter to paste "Bar", it actually outputs "Foo". I assume this is because the visual indicator updates to point to Bar, but internally there is another cursor that is still pointing to Foo that it uses to actually paste.

Using the arrow keys to move the cursor also doesn't seem to help. That is, if I press "down" to highlight Baz, and then "up" to highlight Bar, and then "enter" to paste, I still get Foo.

Hope this makes sense. This is in Sol v1.1.52.

**Comment by ospfranco** [comment]
You are right :) will take care of it later

**Comment by ospfranco** [comment]
Will be there soon

**Comment by ospfranco** [comment]
Should be there 1.1.52
