### ISSUE TITLE
upcoming calendar events are displayed with striketrough title

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#71]
Noticed this before. Not sure if this applies to all upcoming events or if this happens only sporadically. Can say for sure this only happens to the next upcoming event. Events after that do not show with strike-through.

If this is expected, I don't understand what the strike-through would convey.

![upcoming event strikethrough](https://user-images.githubusercontent.com/5708172/186115282-399af9a7-c141-4cf8-afd7-378b6ad06d76.png)

**Comment by ospfranco** [comment]
That's weird, I will take a look later

**Comment by ospfranco** [comment]
Ah woops, has to do with the latest change:

https://github.com/ospfranco/sol/blob/main/macos/sol-macOS/lib/CalendarHelper.swift#L44

I made some mistakes showing the issues and tentative appointments where never shown, now they are but status === 3 equals cancelled not 2 :P

**Comment by ospfranco** [comment]
Should be fixed now

**Comment by foss-** [comment]
Verified in 1.1.55, thank you.
