### ISSUE TITLE
Improve file searches

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#72]
Maybe out of scope for current implementation but sometimes when I search for a word like `searchterm` and I am certain a file exists with the name `searchterm horray`...

**Currrently**
... file search is not invoked and no file search results are presented, only Google Search, Translate and Maps are offered as options.

**Expected**
either file search should automatically be invoked by the search term. Or that could be a 2-step process analog to what Raycast does: As soon as it discovers the search term is not an app name the option `File Search` shows up and once selected the file search is executed.

**Comment by ospfranco** [comment]
File search is always executed, as stated on a previous issue, querying capabilities against the spotlight API are limited. I will leave it open if somebody else wants to give it a go. PRs are welcome.

**Comment by ospfranco** [comment]
I re-wrote file searches now it is under it's own item. Search for `File Search` and then you can do searches. You need to add to folders where to search under settings (⌘ + ,)
