### ISSUE TITLE
1.1.59 crash

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#74]
Version 1.1.59 crashes on the first invoke after opening.

[Crash log](https://bin.disroot.org/?57a950061a20fda8#NXZ5C4iQHznfDPu59WvKm19J8ykxDY76J6FM9dj55YH) (1 month).

Edit: while Sol crashed three times in a row for me with above procedure, it now opens as expected. So now I am unsure what to make to make of the crash. Scratch that it crashed again, although not on the first attempt to invoke.

**Comment by jbergstroem** [comment]
I have a few crashes too across 1.1.5x. Is this issue the best way to pass crash logs or do you prefer input in a more structured way?

**Comment by foss-** [comment]
@jbergstroem Sol comes with sentry so if you have not blocked that crash logs will be sent to the developer of Sol.

**Comment by ospfranco** [comment]
ah, it looks like I introduced some race conditions when I migrated to JSI functions... but I think it should be easily fixable, give me some minutes

**Comment by ospfranco** [comment]
1.1.60 is out, give it a try please

**Comment by foss-** [comment]
1.1.60 still [crashes](https://vomitb.in/Z1Axzgu8N5).

**Comment by ospfranco** [comment]
ok, I will revert the changes, give me some more minutes

**Comment by ospfranco** [comment]
.61 is out, please test it

**Comment by foss-** [comment]
1.1.61 looking good.
