### ISSUE TITLE
emoji search is not finding expected emojis

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#78]
When searching for 💯 emoji and typing `100` Sol shows `No emoji found`. Frequently ran into this problem with other emojis as well like when searching for 🙏 using `thank` or `pray`.
![emoji search](https://user-images.githubusercontent.com/5708172/187908206-ba641f11-af99-4531-8fb3-477f0acc6c3b.png)

**Comment by ospfranco** [comment]
The emoji list is probably not complete, I just took a random one I found online:

https://github.com/ospfranco/sol/blob/main/src/lib/emojis.json

Feel free to submit a PR with the missing ones or I can take a look later

**Comment by foss-** [comment]
both emojies are in the list. It is just that the search terms don't bring up the expected emoji.

**Comment by ospfranco** [comment]
Ok, I added the aliases to the search term list `100` and `pray` now work.

**Comment by foss-** [comment]
1.1.62
💯🙏
