### ISSUE TITLE
Strange behavior with the reload

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#8]
Hi @ospfranco , when I reload I get these strange behaviors:
- Audio I was listening to can no longer be seen below
- Standard applications are not shown

To return to how I was before I have to close the app (esc key) and reopen it.

https://user-images.githubusercontent.com/20476002/159160854-403d3ec4-a1a0-48a2-b373-bd07d9352207.mov

**Comment by ospfranco** [comment]
yes, the app loads the native queries when the onShown listener is called, doing a hard reload causes the cache to be emptied, this is only an issue while developing the app
