### ISSUE TITLE
Allow navigating calendar events with left | right arrow keys also

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#80]
**Currently**

When tabbing into calendar events, it is only possible to navigate between events.

**Expected**

Since the design change and now events being displayed in a single row, it would be more intuitive to allow ffor navigation using left | right arrow keys. Up | down can be kept I guess.

**Comment by ospfranco** [comment]
I didn't have the energy to do it yesterday too, it will be released shortly

**Comment by foss-** [comment]
1.1.69 verified, thank you.
