### ISSUE TITLE
Question: is there still a UI indicator for calendar event attendance

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#83]
Unsure how exactly event attendance works, since the different calendar implementations seem to differ in their assumptions about that. Add cross-OS sync and debugging becomes so much fun.

However with the new row UI in Sol for calendar events, the attendance dots are gone. Does that mean there is no longer any differentiation? Please just close this issue, after answering - just wondering if a differentiator would be coming back or not or if I am missing something in the current UI in 1.1.69.

**Comment by ospfranco** [comment]
Chose to remove it for now, it's also confusing without a clear symbol that indicates participation. Maybe it will come back in the future, but for now I like it better.
