### ISSUE TITLE
Calendar Events: shows no events on search results

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#84]
macOS 12.5.1
Sol 1.1.69

**Currently**

Calendar events show fine on invoking Sol. After searching for something the calendar event list shows `No Events` for all days despite existing events. Always reproducible here.

**Expected**

Guess calendar events should be shown correctly. Although I am not sure if I would expect calendar events to show at all in search results view. Having calendar events in initial view is great, but if a user wanted to interact with calendar events they would do so from that view. Would suggest to remove calendar events from search results view.

**Comment by ospfranco** [comment]
The search term applies not only to the main results, but also to the events. The idea was to quickly look up events for the coming days. But now that the view is limited to 5 days, it might not be all day useful. I will leave it for now, maybe will change my mind later and implement something different.

**Comment by foss-** [comment]
Oh I see. Could you remove case sensitivity for Calendar events then?

**Comment by ospfranco** [comment]
already done in the latest version

**Comment by foss-** [comment]
> already done in the latest version

Verified in 1.1.70.
