### ISSUE TITLE
Search for third party system preference panes

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#85]
Feel free to close if out of scope, but being able to search for system preferences components would be a useful addition.

**Comment by ospfranco** [comment]
They are already there, are they not?

**Comment by foss-** [comment]
Correct, the remaining aspect would be third party system preference panes as exist for ChronoAgent, macFUSE or GPG Suite to name a few. (adjusting title accordingly)

**Comment by ospfranco** [comment]
I don't quite understand what you mean... do you want to open a third party app settings window? is that even possible?

Or do you mean searching for menu bar items? I think Raycast does this, it is cool but no idea and no time to implement it.

**Comment by foss-** [comment]
It is possible for apps to install a preference pane for some settings. ChronoAgent is one example:
![1](https://user-images.githubusercontent.com/5708172/189356867-29b14b82-efd3-4cc6-8176-2f32a9576bc4.png)

**Comment by ospfranco** [comment]
ah ok. I don't know if it is possible to programmatically get system prefs panels, current implementation has hardcoded paths. Will leave this ticket open for now, but someone else will have to implement it.

**Comment by OlshaMB** [comment]
There are 3 locations for them:

1. `/System/Library/PreferencePanes/`
2. `/Library/PreferencePanes`
3. `/Users/**USER**/Library/PreferencePanes`

**Comment by ospfranco** [comment]
PRs are welcome

**Comment by ospfranco** [comment]
Are this third party panels still supported on Ventura? the new app seems a lot less native than previous implementations, I had to hardcode the new paths and there seems to be no new documentation.

**Comment by foss-** [comment]
Yes, they may look a bit weird since their old UI doesn't fit the new style but they still existing and load as expected. You could test with e.g. https://osxfuse.github.io/

**Comment by foss-** [comment]
Great news. Verified this works for `ChronoAgent`.

It did not work for `macFUSE` or `GPGPreferences` (comes with GPG Suite).
<img width="659" alt="1" src="https://user-images.githubusercontent.com/5708172/204108536-8a8bba3f-8f10-4ff8-9667-4e14be2bb8d7.png">

**Comment by ospfranco** [comment]
I used the method suggested by @OlshaMB. No idea how macFuse is adding preference panes.

**Comment by ospfranco** [comment]
On the GPGPreferences github readme they say you need to manually copy the .prefPane file to ~/Librare/PreferencePanes, if you do that, it should work. As for macFuse, no idea.

**Comment by ospfranco** [comment]
<img width="740" alt="Screenshot 2022-11-27 at 09 54 03" src="https://user-images.githubusercontent.com/1634213/204126837-5f00c284-c5b1-4066-a97a-0a69ec572db7.png">

macFUSE is there, it only has a funny parsing due to the way I generate the names :)

**Comment by foss-** [comment]
Wow at macFUSE for using the most unexpected parsing. Confirming it works as intended. Thanks for adding this.
