### ISSUE TITLE
Ability to disable certain features

### ISSUE THREAD

**Issue by OlshaMB** [ospfranco/sol#87]
# Ability to disable certain features
I want to be able disable clipboard manager. And also disable certain search result types like google maps search. And also hide certain apps from search

**Comment by ospfranco** [comment]
PRs are welcome

**Comment by ospfranco** [comment]
You can now disable the clipboard manager and scratch-pad shortcuts from the settings.

<img width="750" alt="CleanShot 2023-03-05 at 04 39 25" src="https://user-images.githubusercontent.com/1634213/222940397-dad6491a-21a2-4943-a62b-b39edfa8ac05.png">
