### ISSUE TITLE
Opinion: make overlay optional

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#88]
Personally not a big fan of the overlay once Sol opens. Clearly subjective and opinionated comment so going to close this, but maybe this can serve to gather feedback from others.

I think the reason neither Raycast nor LaunchBar use an overlay is, to interfere as little as possible. The overlay distracts more than it helps focus I think. And unsure whether the idea of focus is really wanted in a launcher.

**Comment by ospfranco** [comment]
I'll add a toggle for it

**Comment by ospfranco** [comment]
Removed the overlay for now, no time to properly fix it
