### ISSUE TITLE
Strange problem with scaling

### ISSUE THREAD

**Issue by Angelk90** [ospfranco/sol#9]
Hi @ospfranco , as you can see I am testing in all ways sol.

I tried to resize it as seen from the video and I get this result.

The problem is that I can't get back to its original shape or try to shrink everything after enlarging the app.

https://user-images.githubusercontent.com/20476002/159161108-ede818b0-c0f0-4864-9dd1-97c07d563311.mov

**Comment by ospfranco** [comment]
the window is not meant to be resizable, feel free to open a PR though, this is minor

**Comment by Angelk90** [comment]
@ospfranco : Would it be possible to make sure that it is not resized?

**Comment by ospfranco** [comment]
ok, should be fixed
