### ISSUE TITLE
How to manage shortcuts

### ISSUE THREAD

**Issue by huabin** [ospfranco/sol#90]
Hello,

Sorry to trouble you, is there a place to manage shortcuts on sol? 

Thank you.

**Comment by ospfranco** [comment]
click on the sol icon --or-- cmd + comma or search for "settings". Not all shortcuts are editable and not all functionality can be currently turned off.

**Comment by huabin** [comment]
@ospfranco 

Thank you so much. But there doesn't seem to be a place to manage self-created shortcuts.

**Comment by ospfranco** [comment]
There is currently not

**Comment by huabin** [comment]
Got it, thank you.
