### ISSUE TITLE
add option to not autostart Sol on launch

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#91]
While Sol is a launcher and chances are, users want it active all the time, there might be cases where users don't want Sol to launch, but may switch back to using it and don't want to uninstall. Having an option to prevent autostart would be welcome since Sol is not showing under System Preferences > Users & Groups > Login Items.

**Comment by ospfranco** [comment]
Do you actually need this? or just hypotethical?

**Comment by foss-** [comment]
I need it. Using three launchers currently. Please don't ask why and not the average use-case. Since things can get confusing, I'd like to temporarily disable Sol but don't want to uninstall and lose weather settings etc

**Comment by ospfranco** [comment]
Well... a launcher that does not auto launch on start is definitely an edge-case, that being said: PRs are welcome :)

**Comment by ospfranco** [comment]
Option is now there on the settings menu. Let me know if it works.

**Comment by foss-** [comment]
Can you point to to a download? Running into https://github.com/ospfranco/sol/issues/93 and https://github.com/ospfranco/sol/releases/tag/1.1.84 does not include a binary.

**Comment by ospfranco** [comment]
releases folder here on the repo or install view brew

**Comment by foss-** [comment]
Downloads at https://github.com/ospfranco/sol/tree/main/releases
Was looking at https://github.com/ospfranco/sol/tags which does not seem to include binaries.

Verified in 1.1.84, thanks.
