### ISSUE TITLE
Persistent Clipboard History

### ISSUE THREAD

**Issue by hwbehrens** [ospfranco/sol#92]
I'm not sure if this enhancement has been requested before, but it would be a nice quality-of-life improvement if the backing store in Sol persisted between restarts.

I often rely on my clipboard history as a kind of long-term, backup 'undo' queue when I'm coding, but if I happen to power-cycle my machine or get a Sol update overnight, I lose all that history and start the following day with less working context.

I don't particularly care if that goes to a sqlite store or even a plaintext file, since the underlying volume is already encrypted at rest, but for those users more paranoid than I perhaps it should be an option.

In any case, thanks so much for all your hard work! Sol is already really great.

**Comment by ospfranco** [comment]
This makes a lot of sense. I added support for it, please do test in the latest version (1.1.79), let me know if you find any issues with it.
![Screenshot 001073](https://user-images.githubusercontent.com/1634213/194015885-da835d7b-27c8-4cc7-a6ef-a0773ccd520a.png)

**Comment by ospfranco** [comment]
Scratch that for a bit, I'm having troubles with getting the app signed by apple, will let you know once I release it

**Comment by ospfranco** [comment]
Ok it is released now under 1.1.83

**Comment by hwbehrens** [comment]
Perfection! It's working great -- exactly what I needed.
