### ISSUE TITLE
1.1.94 crashing - updater failing to replace app, crash soon after open after manual install, app not signed

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#97]
1.1.94 crashes soon after opening: [crash log (1week)](https://bin.disroot.org/?68bfeae1ea413cd4#H8Wjnf8GBnmN2gT1CV6H3cxWyNyYrSf572SeYQsNp3QC)

Sidenote: Was unable to update via sol app. After placing sol app into applications folder it complains about being unsigned when trying to open. Could that also be the reason why the update did not work?

**Comment by ospfranco** [comment]
weird, the notarization process did succeed, I'm uploading version 1.1.95 right now, give that one a try

**Comment by foss-** [comment]
Updating from 1.1.94 to 1.1.95 seemed to work. Sparkle found the update, downloaded it. But then I saw a brief warning (I think about opening an unsigned app, but not sure, since the dialog was shown very briefly) and when I wanted to take a closer look at sol.app it was not in application folder. So updater did not manage to replace the app it seems.

Downloaded https://github.com/ospfranco/sol/blob/main/releases/1.1.95.zip
```
codesign -dv --verbose=4 /Applications/Sol.app 
Executable=/Applications/Sol.app/Contents/MacOS/sol
Identifier=com.ospfranco.sol
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20500 size=30557 flags=0x10000(runtime) hashes=944+7 location=embedded
VersionPlatform=1
VersionMin=659200
VersionSDK=787200
Hash type=sha256 size=32
CandidateCDHash sha256=0a214b921372a52486e4a143b4fbf4fedc8eaeb5
CandidateCDHashFull sha256=0a214b921372a52486e4a143b4fbf4fedc8eaeb5a0db156c673e0421e207d343
Hash choices=sha256
CMSDigest=0a214b921372a52486e4a143b4fbf4fedc8eaeb5a0db156c673e0421e207d343
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=2703360
Executable Segment flags=0x1
Page size=4096
Launch Constraints:
	None
CDHash=0a214b921372a52486e4a143b4fbf4fedc8eaeb5
Signature size=8974
Authority=Developer ID Application: Oscar Franco (24CMR7378R)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=3. Nov 2022 at 07:08:53
Info.plist entries=33
TeamIdentifier=24CMR7378R
Runtime Version=12.3.0
Sealed Resources version=2 rules=13 files=149
Internal requirements count=1 size=212
```

When manually opening Sol macOS complains `“Sol” cannot be opened because the developer cannot be verified.`

**Comment by ospfranco** [comment]
dunno, are you sure your machine is not blocking requests to apple's authorization/notarization system?

**Comment by foss-** [comment]
Not seeing upgrading issues for other apps. Sentry for Sol is blocked, but that should not be relevant at that stage of updating sol.

**Comment by ospfranco** [comment]
Apparently notarization is broken with Fastlane... yay... I uploaded a manually built 1.1.96, try that one please

**Comment by foss-** [comment]
https://github.com/ospfranco/sol/blob/main/releases/1.1.96.zip works

**Comment by ospfranco** [comment]
cool, thanks for reporting, I will keep it open until I figure out what broke on fastlane.

**Comment by ospfranco** [comment]
notifications are a weird beast, let me check sentry to see if there is anything obvious

**Comment by ospfranco** [comment]
I see there is a problem, unfortunately I have no stack trace, which applications do you use? Did you give sol full disk access?

**Comment by ospfranco** [comment]
@hwbehrens if you run this command:

```
lsof -p $(ps aux | grep -m1 usernoted | awk '{ print $2 }')| awk '{ print $NF }' | grep 'db2/db$' | xargs dirname
```

What is the output of your console? Which macOS version are you using?

**Comment by ospfranco** [comment]
There is a new version 1.9.99. Contains minor code changes and some debug information for me. Give it a try.

**Comment by hwbehrens** [comment]
> @hwbehrens if you run this command:
> 
> ```
> lsof -p $(ps aux | grep -m1 usernoted | awk '{ print $2 }')| awk '{ print $NF }' | grep 'db2/db$' | xargs dirname
> ```
> 
> What is the output of your console? Which macOS version are you using?

/private/var/folders/rb/x6dbd4812yg6x6wltybflxm40000gn/0/com.apple.notificationcenter/db2

This is on Ventura 22A380.

**Comment by hwbehrens** [comment]
> There is a new version 1.9.99. Contains minor code changes and some debug information for me. Give it a try.

I tried it with notifications enabled, and it's still crashing. Hopefully the logs will be useful.

**Comment by ospfranco** [comment]
@hwbehrens unfortunately not, apparently sentry is not happy collecting native breadcrumbs. Anyways, closing this issue, as this is not related to crashes with notifications. Going to open a new issue.
