### ISSUE TITLE
Enabling notifications crashes the app

### ISSUE THREAD

**Issue by ospfranco** [ospfranco/sol#98]
Apparently some notifications are crashing for some users. Not able to reproduce so far, it would be great if someone can tell me which apps/notifications they have open when the app crashes.

**Comment by hwbehrens** [comment]
What's the best way to collect this information at the granularity that would be useful? I can't imagine that dumping `ps aux` to a file is necessarily going to be very helpful.

**Comment by ospfranco** [comment]
send me a screenshot of the notifications in the notification center, just to see what is in there, you can black out the contents, but I want to see the apps

**Comment by hwbehrens** [comment]
<img width="367" alt="Screenshot 2022-11-11 at 09 12 35" src="https://user-images.githubusercontent.com/6589744/201413630-013a0892-0b87-4da9-aac8-79a113ddc5ea.png">

**Comment by ospfranco** [comment]
Nothing looks out of the ordinary to me, I've also experienced some crashes but the moment I start the app with the debugger attached, I'm unable to find anything... weird

**Comment by ospfranco** [comment]
This feature is hacky anyways, it is bound to break anytime since I'm not using any official API but rather reading directly from the notifications database. I think I will remove it, it's more trouble that it is worth.
