### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by reuseman** [ospfranco/sol#99]
Hey @ospfranco, the work looks very interesting and especially a viable opensource alternative to Raycast. It would be interesting if Sol could run on Linux as well. It is a pity that it is not available. Of course, I know that making multiple platforms work would add to the complexity of the project, however, I saw that you have started to do something for windows support.

ULauncher, Cerebro and Alfred are currently available on Linux, but they don't have this kind of more functional UI. The important thing would be to point out to the community that development on Linux, at first, is not on par with development on macOS, so as not to put the product in a bad light.

Good work :)

**Comment by ospfranco** [comment]
Unfortunately, react native does not work directly on Linux. I also don't have the time to move this forward, so somebody else needs to tackle it. I also did not work on the windows support, somebody else started but dropped it after a while.
